name: Update Portfolios

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Allows the workflow to write to the repository

jobs:
  get-portfolios:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # Step 4: Run Python script to generate portfolio.json
    - name: Run Python script
      run: |
        python assets/python/collect_portfolios.py

    # Step 5: Commit and push all new and modified files if there are changes
    - name: Commit and push changes if detected
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Stage all changes (new, modified, and deleted files)
        git add -A
        
        # Check if there are changes to commit
        if git diff --cached --exit-code; then
          echo "No changes detected, skipping commit and push."
        else
          git commit -m "Update portfolio and related files"
          git push
        fi